# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/song/dev/cpp/qt/serialport/settingdialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(320, 240)
        SettingDialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_portname = QtWidgets.QLabel(SettingDialog)
        self.label_portname.setObjectName("label_portname")
        self.horizontalLayout_15.addWidget(self.label_portname)
        self.comboBox_portname = QtWidgets.QComboBox(SettingDialog)
        self.comboBox_portname.setObjectName("comboBox_portname")
        self.horizontalLayout_15.addWidget(self.comboBox_portname)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_baudrate = QtWidgets.QLabel(SettingDialog)
        self.label_baudrate.setObjectName("label_baudrate")
        self.horizontalLayout_16.addWidget(self.label_baudrate)
        self.comboBox_baudrate = QtWidgets.QComboBox(SettingDialog)
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_baudrate)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_databits = QtWidgets.QLabel(SettingDialog)
        self.label_databits.setObjectName("label_databits")
        self.horizontalLayout_14.addWidget(self.label_databits)
        self.comboBox_databits = QtWidgets.QComboBox(SettingDialog)
        self.comboBox_databits.setObjectName("comboBox_databits")
        self.comboBox_databits.addItem("")
        self.comboBox_databits.addItem("")
        self.comboBox_databits.addItem("")
        self.comboBox_databits.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_databits)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_parity = QtWidgets.QLabel(SettingDialog)
        self.label_parity.setObjectName("label_parity")
        self.horizontalLayout_13.addWidget(self.label_parity)
        self.comboBox_parity = QtWidgets.QComboBox(SettingDialog)
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_parity)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_stopbits = QtWidgets.QLabel(SettingDialog)
        self.label_stopbits.setObjectName("label_stopbits")
        self.horizontalLayout_18.addWidget(self.label_stopbits)
        self.comboBox_stopbits = QtWidgets.QComboBox(SettingDialog)
        self.comboBox_stopbits.setObjectName("comboBox_stopbits")
        self.comboBox_stopbits.addItem("")
        self.comboBox_stopbits.addItem("")
        self.comboBox_stopbits.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_stopbits)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_flowcontrol = QtWidgets.QLabel(SettingDialog)
        self.label_flowcontrol.setObjectName("label_flowcontrol")
        self.horizontalLayout_17.addWidget(self.label_flowcontrol)
        self.comboBox_flowcontrol = QtWidgets.QComboBox(SettingDialog)
        self.comboBox_flowcontrol.setObjectName("comboBox_flowcontrol")
        self.comboBox_flowcontrol.addItem("")
        self.comboBox_flowcontrol.addItem("")
        self.comboBox_flowcontrol.addItem("")
        self.horizontalLayout_17.addWidget(self.comboBox_flowcontrol)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingDialog)
        self.buttonBox.accepted.connect(SettingDialog.accept)
        self.buttonBox.rejected.connect(SettingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Dialog"))
        self.label_portname.setText(_translate("SettingDialog", "Port name : "))
        self.label_baudrate.setText(_translate("SettingDialog", "Baud rate : "))
        self.comboBox_baudrate.setItemText(0, _translate("SettingDialog", "1200"))
        self.comboBox_baudrate.setItemText(1, _translate("SettingDialog", "2400"))
        self.comboBox_baudrate.setItemText(2, _translate("SettingDialog", "4800"))
        self.comboBox_baudrate.setItemText(3, _translate("SettingDialog", "9600"))
        self.comboBox_baudrate.setItemText(4, _translate("SettingDialog", "19200"))
        self.comboBox_baudrate.setItemText(5, _translate("SettingDialog", "38400"))
        self.comboBox_baudrate.setItemText(6, _translate("SettingDialog", "57600"))
        self.comboBox_baudrate.setItemText(7, _translate("SettingDialog", "115200"))
        self.comboBox_baudrate.setCurrentText(_translate("SettingDialog", "115200"))

        self.label_databits.setText(_translate("SettingDialog", "Data bits : "))
        self.comboBox_databits.setItemText(0, _translate("SettingDialog", "5"))
        self.comboBox_databits.setItemText(1, _translate("SettingDialog", "6"))
        self.comboBox_databits.setItemText(2, _translate("SettingDialog", "7"))
        self.comboBox_databits.setItemText(3, _translate("SettingDialog", "8"))
        self.comboBox_databits.setCurrentText(_translate("SettingDialog", "8"))

        self.label_parity.setText(_translate("SettingDialog", "Parity : "))
        self.comboBox_parity.setItemText(0, _translate("SettingDialog", "NoParity"))
        self.comboBox_parity.setItemText(1, _translate("SettingDialog", "EvenParity"))
        self.comboBox_parity.setItemText(2, _translate("SettingDialog", "OddParity"))
        self.comboBox_parity.setItemText(3, _translate("SettingDialog", "SpaceParity"))
        self.comboBox_parity.setItemText(4, _translate("SettingDialog", "MarkParity"))
        self.label_stopbits.setText(_translate("SettingDialog", "Stop bits : "))
        self.comboBox_stopbits.setItemText(0, _translate("SettingDialog", "OneStop"))
        self.comboBox_stopbits.setItemText(1, _translate("SettingDialog", "OneAndHalfStop"))
        self.comboBox_stopbits.setItemText(2, _translate("SettingDialog", "TwoStop"))
        self.comboBox_stopbits.setCurrentText(_translate("SettingDialog", "TwoStop"))

        self.label_flowcontrol.setText(_translate("SettingDialog", "Flow control : "))
        self.comboBox_flowcontrol.setItemText(0, _translate("SettingDialog", "NoFlowControl"))
        self.comboBox_flowcontrol.setItemText(1, _translate("SettingDialog", "HardwareControl"))
        self.comboBox_flowcontrol.setItemText(2, _translate("SettingDialog", "SoftwareControl"))

